service: ${file(package.json):name}

provider:
  versionFunctions: false
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  stage: ${opt:stage, 'development'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  timeout: 10
  memorySize: 128
  deploymentBucket: ${file(infrastructure/terraform-state.json):serverless_s3_bucket}
  role: ${file(infrastructure/terraform-state.json):lambda_role_arn}

  tags: ${file(infrastructure/terraform-state.json):tags}
  stackTags: ${file(infrastructure/terraform-state.json):tags}

functions:
  csv-to-json:
    handler: src/server/handlers/csv-to-json/index.handler

plugins:
  - serverless-webpack

package:
  individually: false
  exclude:
    - node_modules/**
  excludeDevDependencies: true

custom:
  webpack:
    webpackConfig: infrastructure/webpack/webpack.config.server.js
    # Uncomment includeModules if you stop using the serverless-layers plugin
    # includeModules: true

#  associateWaf:
#    name: https://${file(infrastructure/terraform-state.json):regional_web_acl_id}
#    version: V2
#
#  serverless-layers:
#    dependenciesPath: ./build/server/service/package.json
#
#  serverless-offline:
#    port: 3000
#    httpsProtocol: "infrastructure/ssl-certs/localhost"
#    useChildProcesses: true
#
